language: php

notifications:
  email: false
  slack: samerior:FnuAd61tv6oF3C8GdrEFRAoo

php:
  - 7.1
  - 7.2

sudo: false

before_install:
  - composer global require samerior/mobile-money:dev-develop

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
#  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit --verbose

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
